name: pytorch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - numpy
  - pillow
  - matplotlib
  - seaborn
  - scikit-learn
  - pandas
  - fastapi
  - uvicorn
  - python-multipart
  - jupyter
